# Use the official Node.js image as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install -g npm@10.8.3 pnpm

# Copy the rest of the application code
COPY . .

# Build the React app
#RUN npm run build
RUN pnpm i
#RUN npm install http-server
# Serve the app with a static server
#RUN npm install -g serve -n
#RUN pnpm dev
#CMD ["serve", "-s", "build"]
CMD ["pnpm", "dev"]

# Expose port 3000
EXPOSE 3000
